#include "GarmentStudioSkill.h"

UGarmentStudioSkill::UGarmentStudioSkill()
{
	Description = TEXT(
		"Fitting a garment onto a character by sight in MeshForge's Garment Studio: posing the body into the "
		"garment, placing it, looking from several angles, wrapping, judging the wrap from pictures, fixing clips "
		"and finishing. Load when asked to fit, wrap, dress or put clothing on a character with MeshForge, when a "
		"garment clips, floats or sits wrong after a wrap, or when a chain is waiting on the Garment Studio. Needs "
		"an agent that can read images. Optional: a person does this better and faster, so offer it rather than "
		"insist on it.");

	Instructions = TEXT(
		"You work the same window a person would, so say what you are doing: a person may be watching, and may "
		"take over. Every tool takes the definition's path and the fit step's index; -1 finds the first fit step.\n"
		"\n"
		"The loop:\n"
		"1. Open Garment Studio. Read the state: where the garment is, which joints are turned, whether a wrap or "
		"a finished garment already exists. A finished garment on this same garment (bFinishedOnThisGarment) needs "
		"nothing: the chain already hands it on. Stop there unless you were asked to redo it.\n"
		"2. Look before you touch. Capture Garment Studio in PoseAndPlace from Front, then Left and FrontLeft. Read "
		"each PNG with your own image reader. Judge: is the garment around the body at all; is the collar at the "
		"neck; do the sleeves run along the arms; is the hem at the right height; is it worn front to front "
		"(buttons, prints and pockets face the way the face does)?\n"
		"3. Place. If it is nowhere near, Place Garment In Studio with bAutoPlace first. Then adjust in small steps: "
		"location in centimetres in the character's space (Z is up, the character stands at the origin), yaw 180 "
		"for a garment worn back to front, scale so the sleeves reach the wrists and the collar sits on the neck. "
		"Capture after every change.\n"
		"4. Pose. The body bends to meet the garment, not the other way round. Turn the upper arms and elbows "
		"(upperarm_l, lowerarm_l; the right side follows by mirror) a few degrees at a time until the arms run "
		"inside the sleeves; the legs for trousers (thigh_l, calf_l). Close-ups help: capture with FocusJoint set "
		"to the joint you are turning, from Front and from the side it is on.\n"
		"5. Sculpt before the wrap only where the garment itself is wrong for this body: a neck too tight to go "
		"over the head, a hem inside the legs. Capture in Sculpt mode from the view that shows the problem, then "
		"Sculpt Garment In Studio with drags in that picture's coordinates (0..1 from its top-left). A drag must "
		"start on the garment, not beside it; the tool says so when it does not. Small moves; the wrap does the "
		"rest.\n"
		"6. Wrap Garment In Studio and wait for it (about fifteen seconds). Then capture in Wrap mode from Front, "
		"Back, Left and Right. The wrap stands on the body straightened into its reference pose.\n"
		"7. Judge the wrap. Skin showing through cloth is clipping: raise ClearanceCm (1.2 is a shirt on skin; 2 "
		"to 3 for a jacket) or use FitStyle Loose, and wrap again. Cloth floating far off the body: lower the "
		"clearance or use Slim. A sleeve twisted or pulled across the chest: the arm was not inside it; go back to "
		"the pose. A collar or hem crushed: sculpt before the wrap. Read WrapSummary too: it says how many vertices "
		"are still inside the body after the last pass.\n"
		"8. A small clip the settings cannot fix can be pushed out on the wrap itself: capture in Wrap mode and "
		"sculpt there. Wrapping again replaces that sculpt, so do it last.\n"
		"9. Finish Garment Studio when the wrap looks right and is not out of date (bWrapOutOfDate false). The "
		"chain takes it from there. Do not finish an out-of-date wrap to save time; wrap again.\n"
		"\n"
		"Stop and hand over to a person, with the paths of the pictures that show the problem, when five wraps have "
		"not converged, when the garment is the wrong kind for the body (a helmet on a torso), or when the garment "
		"itself is broken - holes, a body inside it, pieces missing. Those are for a person or for regenerating the "
		"garment, not for fitting.\n"
		"\n"
		"Change one thing at a time and look after each, or you will not know what helped. Captures are plain files "
		"under the project's Saved folder; nothing else is written until you save or finish. Save Garment Studio "
		"keeps your work without finishing. Close Garment Studio with bSave false drops what was not saved.");
}
